import Head from 'next/head'
import style from '@/styles/Home.module.scss'
import Link from 'next/link';
import Image from 'next/image';
// Images
import teams from '../../public/trustedteams.png';
import DashbaordImg from '../../public/dashboard_Img.png';
import paymentImg from '../../public/payments_balance.png';
import surveyImg from '../../public/surverys_data.png';
import scImg from '../../public/solution_img.png';
import quote from '../../public/quote_img.png';
import code from '../../public/code_img.png'
// Icons
import arrowRight from '../../public/icons/arrow_circle_right.svg';
import caratLeft from '../../public/icons/chevron-left.svg';
import caratRight from '../../public/icons/chevron-right.svg';
import redArrow from '../../public/icons/solution_arrow_right.svg';
import slack from '../../public/icons/slack_logo.png';
import twoWay from '../../public/icons/two_way_arrow.svg';
import openRate from '../../public/icons/open_rates.svg';
import personal from '../../public/icons/sender.svg';
import flash from '../../public/icons/flash.svg';
import shield from '../../public/icons/shield.svg';
import circleCheck from '../../public/icons/check_circle.svg';
import boxedCheck from '../../public/icons/boxed_check.svg';
import linkarrow from '../../public/icons/link_arrow.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>HollaTags -- home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <section className={style.hero}>
            <h1 className={style.introText}>Messaging Platforms and APIs for communication on mobile via VOICE, SMS, USSD and Mobile</h1>
            <p className={style.subText}>We&apos;re taking digital experiences up a notch! building the APIs and platforms to securely interface with your audience and drive connectivity.</p>
            <div className={style.cta_row}>
                <Link href="" id="firstLink">
                    Get Started 
                    <Image src={arrowRight} alt="" 
                />
                </Link>
                <Link href="">Speak to Sales</Link>
            </div>
        </section>
        <section className={style.socialProof}>
            <p className={style.intro}>
                Trusted By the Best teams
            </p>
            <Image src={teams} alt="" id={style.comImg} />
            <Image src={DashbaordImg} alt=""  id={style.dashImg}/>
        </section>
        <section className={style.products}>
            <div className={style.intro}>
                <h1>Our Products</h1>
                <p>One size may not fit all, see which hollatags products help your business excel</p>
            </div>
            <div className={style.toggle_row}>
                <p className={style.toggle_element}>SMS</p>
                <p className={style.toggle_element}>USSD</p>
                <p className={style.toggle_element}>IVR</p>
                <p className={style.toggle_element}>Carrier Billing</p>
            </div>
            <div className={style.toggle_content}>
                <div className={style.sms}>
                    <div className={style.sms_content}>
                        <div className={style.smLeft}>
                            <Image src={paymentImg} alt="" />
                            <h1>Payments & Checks</h1>
                            <p>Implement mobile P2P or utility payments that allow your customers to check their account balance and perform other unique transactions seamlessly using the HollaTags USSD platform. </p>
                        </div>
                        <div className={style.smRight}>
                            <Image src={surveyImg} alt="" />
                            <h1>Surveys and Data Collection</h1>
                            <p>Conduct mobile research polls/surveys using USSD, it is universally available on any mobile phone. HollaTags makes this possible via a dedicated or shared USSD code. </p>
                        </div>
                    </div>
                    <Link href='' className={style.learn_btn}>
                        Learn More
                    </Link>
                </div>
            </div>
        </section>
        <section className={style.solutions}>
            <h1>Business Solutions for client & Partners</h1>
            <div className={style.solution_container}>
                <Image src={caratLeft} alt="" className={style.switch_btn} />
                <div className={style.solutionContent}>
                    <Image src={quote} alt="" id={style.quoteImg} />
                    <Image src={scImg} alt="" className={style.sc_image} />
                    <div className={style.sc_content}>
                        <p id={style.intro}>
                            <Image src={slack} alt="" />
                            Slack
                        </p>
                        <p id={style.comment}>
                            We needed consistency, a network that can deliver 99% of the time and we found that with HollaTags they&apos;ve really helped of keep losses in engagement to a minimum in turn profit has risen.
                        </p>
                        <div>
                            <p id={style.commenter}>Kemi Ukuama</p>
                            <p id={style.commenter_position}>Brand strategist, Slack</p>
                        </div>
                        <Link href=''>
                            Explore Our solutions for partner
                            <Image src={redArrow} alt="" />
                        </Link>
                    </div>
                </div>
                <Image src={caratRight} alt="" className={style.switch_btn} />
            </div>
            <div className={style.indicators}>
                <div className={style.indicator}></div>
                <div className={style.indicator}></div>
                <div className={style.indicator}></div>
                <div className={style.indicator}></div>
                <div className={style.indicator}></div>
            </div>
        </section>
        <section className={style.info}>
            <div className={style.info_content}>
                <div className={style.info_group}>
                    <Image src={twoWay} alt="" />
                    <p id={style.intro}>Two-way SMS</p>
                    <p id={style.content}>
                        We employ best practices when it comes to security and we apply stern policies to ensure safe usage of our services.
                    </p>
                </div>
                <div className={style.info_group}>
                <Image src={openRate} alt="" />
                    <p id={style.intro}>Open Rates</p>
                    <p id={style.content}>
                    Strict privacy policies that ensure that customer data is handled by only a select few with strict regards for the client’s privacy.
                    </p>
                </div>
                <div className={style.info_group}>
                    <Image src={personal} alt="" />
                    <p id={style.intro}>Personal ID Sender</p>
                    <p id={style.content}>
                    Continuous testing, review and improvement of all our systems (Platform / APIs) to prevent hacks and security breaches.
                    </p>
                </div>
                <div className={style.info_group}>
                    <Image src={flash} alt="" />
                    <p id={style.intro}>Flash and unicode Support</p>
                    <p id={style.content}>
                    At HollaTags We only use the best encryptions and authentication on all our services and applications.
                    </p>
                </div>
                <div className={style.info_group}>
                    <Image src={shield} alt="" />
                    <p id={style.intro}>Security</p>
                    <p id={style.content}>
                    We also ensure regulatory compliance with all existing laws, rules, regulations, and guidelines.
                    </p>
                </div>
                <div className={style.info_group}>
                    <Image src={circleCheck} alt="" />
                    <p id={style.intro}>Regulatory Compliance</p>
                    <p id={style.content}>
                    Our systems are protected with rock-solid firewalls to restrict unwanted access both internally and externally
                    </p>
                </div>
            </div>
        </section>
        <section className={style.developer}>
            <div className={style.dev_con}>
                <div className={style.dev_text}>
                    <h2>Designed for Developers</h2>
                    <div className={style.dev_box}>
                        <h5>
                            <Image src={boxedCheck} alt="" />
                            Some text about API advantage
                        </h5>
                        <p>Start integrating with Well-documented APIs that scales with your business requirements</p>
                    </div>
                    <div className={style.dev_box}>
                        <h5>
                            <Image src={boxedCheck} alt="" />
                            Some text about API advantage
                        </h5>
                        <p>Start integrating with Well-documented APIs that scales with your business requirements</p>
                    </div>
                    <div className={style.dev_box}>
                        <h5>
                            <Image src={boxedCheck} alt="" />
                            Some text about API advantage
                        </h5>
                        <p>Start integrating with Well-documented APIs that scales with your business requirements</p>
                    </div>
                    <div className={style.dev_box}>
                        <h5>
                            <Image src={boxedCheck} alt="" />
                            Some text about API advantage
                        </h5>
                        <p>Start integrating with Well-documented APIs that scales with your business requirements</p>
                    </div>
                    <div className={style.dev_box}>
                        <h5>
                            <Image src={boxedCheck} alt="" />
                            Some text about API advantage
                        </h5>
                        <p>Start integrating with Well-documented APIs that scales with your business requirements</p>
                    </div>
                </div>
                <div className={style.dev_img}>
                    <Image src={code} alt="" />
                </div>
            </div>
            <div className={style.links_con}>
                <div className={style.links_text}>
                    <h6>Guide</h6>
                    <p>Follow See how you can get the most out of HollaTags feature rich APIs for your buisness</p>
                    <Link href="">
                        See API documentation
                        <Image src={linkarrow} alt="" />
                    </Link>
                </div>
                <div className={style.links_text}>
                    <h6>Community</h6>
                    <p>Join our developer community and dedicated help channels on slack to get all the answers you need.</p>
                    <Link href="/">
                        Join Slack workspace
                        <Image src={linkarrow} alt="" />
                    </Link>
                </div>
            </div>
        </section>
        <section className={style.form}>
            <h2>We&apos;re here to help</h2>
            <p>Our support team is online 24/7, go ahead shoot us a message </p>
            <form>
                <p className={style.intro}>We&apos;ll reply within a couple of hours guaranteed</p>

                <div className={style.form_group}>
                    <label htmlFor="name">Your Name</label>
                    <input type="text" name="" id="" placeholder="Let's Know who you are" />
                </div>
                <div className={style.form_group}>
                    <label htmlFor="name">Your Email</label>
                    <input type="text" name="" id="" placeholder="Somewhere we can send documents"/>
                </div>
                <div className={style.form_group}>
                    <label htmlFor="name">Your Number</label>
                    <input type="text" name="" id="" placeholder="No spam calls, Promise" />
                </div>
                <div className={style.form_group}>
                    <label htmlFor="name">Your Company</label>
                    <input type="text" name="" id="" placeholder="The name of your establishment" />
                </div>
                <div className={style.form_group}>
                    <label htmlFor="message">Your Message</label>
                    <textarea name="message" id="" rows={15} placeholder="Say anything you like we're great listeners"></textarea>
                </div>
                <div className={style.form_group}>
                    <input type="submit" value="Send Message" />
                </div>
            </form>
        </section>
    </div>
    </>
  )
}
